spring:
  application:
    name: 's3test'

  servlet:
    multipart:
      max-file-size: '20MB'
      max-request-size: '20MB'

cloud:
  aws:
    s3: 'yerim-test-bucket'
    region:
      static: 'ap-northeast-2'
    stack:
      auto: false
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
